version: '3.8'

services:
  db:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_DB=poc
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  db-data:
    driver: local